Implementation Section
teamulster/report pull request #18
Opened 2020-09-22 14:02 UTC by craftamap

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +Google officially supports Kotlin for Android Apps since 2017
apps lowercase

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +Some design choices of the app were slowed down by Kotlins language features.
Kotlin's

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +Using ``Android Studio'', the official IDE for Android development, allowed
Maybe write "integrated development environment (IDE)"

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +\cite{camerax} is Androids newest Library allowing access to the Camera and
library lowercase
camera lowercase

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +allowed to set filters onto the preview image. A library called ``Nitrite''
I'd prefer "apply" instead of "set"

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +In order to train the CNN, which is explained in \ref{sec:methodology}, an
a Python 3 script

2020-09-22 14:10 UTC, limkokyew commented on chapters/implementation.tex
> +Python 3-Script running in an jupyter notebook was utilised.
a Jupyter notebook

2020-09-22 14:11 UTC, AnnaGsell approved these changes

2020-09-22 14:21 UTC, mac641 requested changes
Important: Change writing tense to present and make sure it's consistent throughout the entire text

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +For the implementation of the app, Kotlin was used.
I'd write `The app/soHappy is built using/with Kotlin.`

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +Using ``Android Studio'', the official IDE for Android development, allowed
I'd write `Android Studio, known as the official IDE for Android development, allowed ...`

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +allowed to set filters onto the preview image. A library called ``Nitrite''
Keep the writing tense consistent:
allowed -> allows

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +\cite{nitrite} allowed us to implement an NoSQL-Database
Same as above

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +\cite{camerax} is Androids newest Library allowing access to the Camera and
Writing tense here, too - either use past (`was Android`) or change everything else to present
Androids -> Android's I think
newest -> latest
Library -> library

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +For image analysis, we used the following libraries: For cascade-based face
cascade-based -> cascade based

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +For machine learning based approaches, the official TFLite library was utilised.
Three sentences starting with `For` here, I'd suggest rewriting them to provide a more fluent reading experience 😉

2020-09-22 14:21 UTC, mac641 commented on chapters/implementation.tex
> +Python 3-Script running in an jupyter notebook was utilised.
Python 3-Script, running in an jupyter notebook, was utilised
Python 3-Script -> Python 3 script

2020-09-23 08:14 UTC, limkokyew approved these changes
Good work! Just one suggestion and a minor typo. You have my approval nonetheless.

2020-09-23 08:14 UTC, limkokyew commented on chapters/implementation.tex
> +``[...] a static code analysis tool [...]''\cite{detekt2020} was used.
Not necessary, but you could provide a short description of what linting does, e. g. ensured coding conventions.

2020-09-23 08:14 UTC, limkokyew commented on chapters/implementation.tex
> +`mathplotlib' and `numpy' were used.
"mathplotlib" -> "matplotlib"

2020-09-23 08:24 UTC, mac641 requested changes

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +\texttt{Object}-class are not natively available. This made using the methods
I think this is still a Java issue, therefore: `made` -> `makes`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +(IDE) for Android development, allowed faster development thanks to useful
`allowed` -> `allows`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +``[...] a static code analysis tool [...]''\cite{detekt2020} was used.
`was` -> `is`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +Various libraries were used to help implement the application. Using
`were` -> `are`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +the included build tool ``Gradle'' \cite{gradle} allowed easy management of
`allowed` -> `allows`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +\cite{camerax} is Android's newest library allowing access to the camera and
`newest` -> `latest` is the better fitting word in this case, I think

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +allowed to apply filters onto the preview image. A library called ``Nitrite''
`allowed` -> `allows`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +For image analysis, we used the following libraries: Cascade based face
`used` -> `use`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +For image analysis, we used the following libraries: Cascade based face
By `Cascade`, you mean `Haar Cascade classifiers`?! 😅

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +Python 3 script running in an Jupyter notebook was utilised.
`was utilised` -> `is used`
utilise is somewhat a wrong fit here, I think

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +The Python TensorFlow library was used in combination with `Keras',
`was used` -> `is used`

2020-09-23 08:24 UTC, mac641 commented on chapters/implementation.tex
> +`mathplotlib' and `numpy' were used.
`were used` -> `are used`

2020-09-23 08:31 UTC, diehmlukas approved these changes

2020-09-23 08:44 UTC, mac641 approved these changes

2020-09-23 08:45 UTC, merged