Data Collection
teamulster/report pull request #25
Opened 2020-09-23 13:36 UTC by craftamap

2020-09-23 13:46 UTC, mac641 requested changes

2020-09-23 13:46 UTC, mac641 commented on chapters/methodology.tex
> +class called \texttt{Measurement} will collect multiple detection results as
will collect -> I'd use `gathers`

2020-09-23 13:46 UTC, mac641 commented on chapters/methodology.tex
> +stored into an local database managed by a database manager.
I suggest using `Results of a finished run (successful/unsuccessful) will be stored in a local database.`

2020-09-23 13:46 UTC, mac641 commented on chapters/methodology.tex
> +regulary. \ref{fig:local_database}
`frequently` might be a better fit
in case you disagree, it's spelled `regularly`

2020-09-23 13:46 UTC, mac641 commented on chapters/methodology.tex
> +  \caption{Class diagram describing the relation between measurements, local database and remote server}
I'd start the description by using `This class diagram describes...`

2020-09-23 13:53 UTC, AnnaGsell approved these changes

2020-09-23 21:04 UTC, mac641 requested changes
Sorry for requesting again - just one minor thingy 😅🙈

2020-09-23 21:04 UTC, mac641 commented on chapters/methodology.tex
> +The data stored in this database is also synchronized to a remote server
synchronised

2020-09-24 08:00 UTC, diehmlukas approved these changes

2020-09-24 08:00 UTC, diehmlukas approved these changes

2020-09-24 08:00 UTC, AnnaGsell approved these changes

2020-09-24 08:03 UTC, mac641 approved these changes

2020-09-24 08:10 UTC, limkokyew approved these changes
Some suggestions

2020-09-24 08:10 UTC, limkokyew commented on chapters/methodology.tex
> +class called \texttt{Measurement} gathers multiple detection results as
Did you intend to write "detection results" instead of "`\texttt{DetectionResult}s`"?

2020-09-24 08:10 UTC, limkokyew commented on chapters/methodology.tex
> +Results of a finished run will be stored in a local database.
You could also consider "session" instead of "run"

2020-09-24 08:34 UTC, merged