37.5 Added Architecture
teamulster/report pull request #7
Opened 2020-09-18 13:57 UTC by craftamap

2020-09-19 10:46 UTC, limkokyew reviewed
Very concise! Found a couple of things you can take a look at.

2020-09-19 10:46 UTC, limkokyew commented on chapters/methodology.tex
> +The main goal of the software architecture of soHappy is providing flexability
flexability -> flexibility

2020-09-19 10:46 UTC, limkokyew commented on chapters/methodology.tex
> +Adding an Face- or Smile-Detector based on the technology of liking requires an
an -> a, I think

2020-09-19 10:46 UTC, limkokyew commented on chapters/methodology.tex
> +developer to implement the intended interface. The implementation then can be
Maybe intended -> designated?

"then can be" should be fine, but I think "can then be" sounds a bit better

2020-09-19 10:46 UTC, limkokyew commented on chapters/methodology.tex
> +selected by modifing the configuration file of the app. A Factory Method will
modifing -> modifying
"Factory Method" -> "factory method" (?)

2020-09-20 12:22 UTC, mac641 requested changes
Some consistency issues regarding capitalising certain terms / the use of hyphens -> I'd suggest discussing this on Monday

2020-09-20 12:22 UTC, mac641 commented on chapters/methodology.tex
> +Adding a Face- or Smile-Detector based on the technology of liking requires a
We should stay consistent here. 😁
I'd write face and smile detector uncapitalised (since it is no name), as well as not using a hyphen

2020-09-20 12:22 UTC, mac641 commented on chapters/methodology.tex
> +selected by modifying the configuration file of the app. A configuration-based
I would not use hyphens here as well

2020-09-20 12:22 UTC, mac641 commented on chapters/methodology.tex
> +The Image Analyzer uses the created implementations of Face- and Smile-
Not quite sure if this suits our case, but I'd write image analyzer uncapitalised as well 🤔

2020-09-20 13:09 UTC, diehmlukas approved these changes
I like it

2020-09-20 13:12 UTC, limkokyew commented on chapters/methodology.tex
> +In order to load and manage the configuration file, an configuration manager
"a configuration [...]" instead of "an configuration [...]"

2020-09-20 13:12 UTC, limkokyew commented on chapters/methodology.tex
> +    \caption{class diagram describing the architecture}
Capitalize "class"

Something I didn't realize at first as well is that you must briefly describe every figure in your text, so e. g.: "Figure `\ref{fig:arch1}` shows the class diagram of the architecture". You already have "(See `\ref{fig:arch1}`)" above, but you probably have to provide a more detailed description.

2020-09-20 13:12 UTC, limkokyew commented on chapters/methodology.tex
> +factory will create the Face- or Smile-Detector based on a configuration file.
You are writing configuration twice: "configuration-based" and "based on a configuration file"

2020-09-20 21:54 UTC, AnnaGsell requested changes

2020-09-20 21:54 UTC, AnnaGsell commented on chapters/methodology.tex
> +in switching out various components.
is it really 'switching out'? sounds stange to me, what about 'exchanging'?

2020-09-20 21:54 UTC, AnnaGsell commented on chapters/methodology.tex
> +Adding a Face- or Smile-Detector based on the technology of liking requires a
'liking'?

2020-09-21 14:34 UTC, AnnaGsell reviewed
Would be  nice to explain model-view-viewmodel in this section...

2020-09-22 07:26 UTC, diehmlukas approved these changes

2020-09-22 07:36 UTC, craftamap commented
> Would be nice to explain model-view-viewmodel in this section...

@AnnaGsell done, please rereview!

2020-09-22 07:41 UTC, mac641 approved these changes
One minor consistency/typo thingy (comment) - other than that, it looks good to me :)
Going to approve it nonetheless 👍🏿

2020-09-22 07:41 UTC, mac641 commented on chapters/methodology.tex
> +The image analyzer uses the created implementations of Face- and Smile-
Still `Face-`, `Smile-`...I'd omit the hyphens

2020-09-22 07:59 UTC, AnnaGsell approved these changes

2020-09-22 08:20 UTC, limkokyew approved these changes

2020-09-22 08:37 UTC, merged